default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: hotel_app_development
  username: postgres
  password: benplan1
  
test:
  <<: *default
  database: hotel_app_test
  username: postgres
  password: benplan1

production:
  <<: *default
  database: hotel_app_production
  username: hotel_app
  password: <%= ENV["HOTEL_APP_DATABASE_PASSWORD"] %>
